(ns tiny-drw.codegen
  (:require [clojure.string :as str]
            [tiny-drw.scene :as scene]))

;; tiny-drw.codegen
;;
;; Consolidated code generation helpers for tiny-drw:
;; - C header generation from record schema
;; - SVG -> draw-record conversion

;; ---------------------------------------------------------------------------
;; C header generation from tiny-drw.scene record layouts
;; ---------------------------------------------------------------------------

(def record-layouts
  [{:type-name "Transform" :prefix "TINY_DRW_TRANSFORM" :fields scene/transform-fields}
   {:type-name "Style" :prefix "TINY_DRW_STYLE" :fields scene/style-fields}
   {:type-name "Group" :prefix "TINY_DRW_GROUP" :fields scene/group-fields}
   {:type-name "Line" :prefix "TINY_DRW_LINE" :fields scene/line-fields}
   {:type-name "Polyline" :prefix "TINY_DRW_POLYLINE" :fields scene/polyline-fields}
   {:type-name "Rect" :prefix "TINY_DRW_RECT" :fields scene/rect-fields}
   {:type-name "Tri" :prefix "TINY_DRW_TRI" :fields scene/tri-fields}
   {:type-name "VText" :prefix "TINY_DRW_VTEXT" :fields scene/text-fields}
   {:type-name "Scene" :prefix "TINY_DRW_SCENE" :fields scene/scene-fields}
   {:type-name "FrameScene" :prefix "TINY_DRW_FRAME_SCENE" :fields scene/frame-scene-fields}])

(defn kw->c-token
  [k]
  (-> (name k)
      (str/replace "-" "_")
      (str/upper-case)))

(defn emit-record-enum
  [{:keys [prefix fields]}]
  (let [lines (loop [i 0
                     fs fields
                     out []]
                (if (empty? fs)
                  out
                  (let [field (first fs)
                        line (str "  " prefix "_IDX_" (tiny-drw.codegen/kw->c-token field) " = " i ",")]
                    (recur (+ i 1) (rest fs) (conj out line)))))]
    (str "enum {\n"
         (str/join "\n" lines) "\n"
         "};\n"
         "#define " prefix "_FIELD_COUNT " (count fields) "\n")))

(defn c-header-string
  "Returns generated C header content for tiny-drw.scene record layouts."
  []
  (str "/* Auto-generated by tiny-drw.codegen. */\n"
       "#ifndef TINY_DRW_SCENE_LAYOUT_H\n"
       "#define TINY_DRW_SCENE_LAYOUT_H\n\n"
       (str/join "\n"
                 (map tiny-drw.codegen/emit-record-enum record-layouts))
       "\n#endif /* TINY_DRW_SCENE_LAYOUT_H */\n"))

(defn spit-c-header!
  "Writes generated header to path. Returns path."
  [path]
  (spit path (c-header-string))
  path)

;; ---------------------------------------------------------------------------
;; SVG -> tiny-clj draw-record importer (MVP subset)
;; ---------------------------------------------------------------------------

(defn- ws-char?
  [c]
  (or (= c \space) (= c \tab) (= c \newline) (= c \return)
      (= c 32) (= c 9) (= c 10) (= c 13)))

(defn- skip-ws
  [s i]
  (loop [idx i]
    (if (and (< idx (count s)) (ws-char? (nth s idx)))
      (recur (+ idx 1))
      idx)))

(defn- first-ws-index
  [s]
  (loop [i 0]
    (if (>= i (count s))
      nil
      (if (ws-char? (nth s i))
        i
        (recur (+ i 1))))))

(defn- parse-attrs
  [attrs-str]
  (loop [idx 0
         out {}]
    (let [n (count attrs-str)
          i (skip-ws attrs-str idx)]
      (if (>= i n)
        out
        (let [eq (str/index-of attrs-str "=" i)]
          (if (nil? eq)
            out
            (let [k (str/trim (subs attrs-str i eq))
                  vstart0 (skip-ws attrs-str (+ eq 1))]
              (if (>= vstart0 n)
                out
                (let [q (subs attrs-str vstart0 (+ vstart0 1))]
                  (if (or (= q "\"") (= q "'"))
                    (let [vstart (+ vstart0 1)
                          vend (str/index-of attrs-str q vstart)]
                      (if (nil? vend)
                        out
                        (recur (+ vend 1) (assoc out k (subs attrs-str vstart vend)))))
                    (let [next-ws (first-ws-index (subs attrs-str vstart0))
                          vend (if (nil? next-ws) n (+ vstart0 next-ws))]
                      (recur vend (assoc out k (subs attrs-str vstart0 vend))))))))))))))

(defn- parse-style-inline
  [style-str]
  (if (or (nil? style-str) (= (str/trim style-str) ""))
    {}
    (loop [parts (str/split style-str ";" nil)
           out {}]
      (if (empty? parts)
        out
        (let [chunk (str/trim (first parts))]
          (if (or (= chunk "") (nil? (str/index-of chunk ":" 0)))
            (recur (rest parts) out)
            (let [sep (str/index-of chunk ":" 0)
                  k (str/trim (subs chunk 0 sep))
                  v (str/trim (subs chunk (+ sep 1)))]
              (recur (rest parts) (assoc out k v)))))))))

(defn- attr-get
  [attrs style-map k]
  (let [v (get attrs k)]
    (if (nil? v) (get style-map k) v)))

(defn- truncate-decimal-str
  [s]
  (let [t (str/trim s)
        dot (str/index-of t "." 0)]
    (if (nil? dot) t (subs t 0 dot))))

(defn- parse-int-default
  [s default-value]
  (if (or (nil? s) (= (str/trim s) ""))
    default-value
    (let [token (truncate-decimal-str s)]
      (if (or (= token "") (= token "-") (= token "+"))
        default-value
        (read-string token)))))

(defn- hex-digit-value
  [c]
  (cond
    (or (= c \0) (= c 48)) 0
    (or (= c \1) (= c 49)) 1
    (or (= c \2) (= c 50)) 2
    (or (= c \3) (= c 51)) 3
    (or (= c \4) (= c 52)) 4
    (or (= c \5) (= c 53)) 5
    (or (= c \6) (= c 54)) 6
    (or (= c \7) (= c 55)) 7
    (or (= c \8) (= c 56)) 8
    (or (= c \9) (= c 57)) 9
    (or (= c \a) (= c 97)) 10
    (or (= c \b) (= c 98)) 11
    (or (= c \c) (= c 99)) 12
    (or (= c \d) (= c 100)) 13
    (or (= c \e) (= c 101)) 14
    (or (= c \f) (= c 102)) 15
    (or (= c \A) (= c 65)) 10
    (or (= c \B) (= c 66)) 11
    (or (= c \C) (= c 67)) 12
    (or (= c \D) (= c 68)) 13
    (or (= c \E) (= c 69)) 14
    (or (= c \F) (= c 70)) 15
    :else -1))

(defn- parse-hex2
  [s offset]
  (let [c1 (hex-digit-value (nth s offset))
        c2 (hex-digit-value (nth s (+ offset 1)))]
    (if (or (< c1 0) (< c2 0))
      nil
      (+ (* c1 16) c2))))

(defn- rgb888->rgb565
  [r g b]
  (let [r5 (quot (* r 31) 255)
        g6 (quot (* g 63) 255)
        b5 (quot (* b 31) 255)]
    (+ (* r5 2048) (* g6 32) b5)))

(defn- parse-color-rgb565
  [s]
  (if (nil? s)
    nil
    (let [t (str/lower-case (str/trim s))]
      (cond
        (or (= t "") (= t "none")) nil
        (and (= (count t) 7) (= (subs t 0 1) "#"))
        (let [r (parse-hex2 t 1)
              g (parse-hex2 t 3)
              b (parse-hex2 t 5)]
          (if (or (nil? r) (nil? g) (nil? b))
            nil
            (rgb888->rgb565 r g b)))
        :else nil))))

(defn- style-from-svg
  [attrs style-map]
  (let [stroke (parse-color-rgb565 (attr-get attrs style-map "stroke"))
        fill (parse-color-rgb565 (attr-get attrs style-map "fill"))
        stroke-rgb565 (if (nil? stroke) (if (nil? fill) 65535 fill) stroke)
        stroke-width (max 1 (parse-int-default (attr-get attrs style-map "stroke-width") 1))
        display (str/lower-case (str/trim (or (attr-get attrs style-map "display") "")))
        visibility (str/lower-case (str/trim (or (attr-get attrs style-map "visibility") "")))
        visible (not (or (= display "none") (= visibility "hidden")))]
    (record-create scene/style-type [stroke-rgb565 stroke-width visible false 0])))

(defn- parse-points
  [points-str]
  (let [normalized (-> points-str
                       (str/trim)
                       (str/replace "\n" " ")
                       (str/replace "\t" " ")
                       (str/replace "  " " "))
        tokens (str/split normalized " " nil)]
    (loop [xs tokens
           out []]
      (if (empty? xs)
        out
        (let [token (str/trim (first xs))]
          (if (= token "")
            (recur (rest xs) out)
            (let [xy (str/split token "," nil)]
              (if (< (count xy) 2)
                (recur (rest xs) out)
                (recur (rest xs)
                       (conj out [(parse-int-default (first xy) 0)
                                  (parse-int-default (nth xy 1) 0)]))))))))))

(defn- node-from-tag
  [tag-name attrs style-map node-id]
  (let [style (style-from-svg attrs style-map)
        visible (get style :visible)]
    (cond
      (= tag-name "line")
      (record-create scene/line-type
                     [node-id
                      nil
                      style
                      visible
                      (parse-int-default (get attrs "x1") 0)
                      (parse-int-default (get attrs "y1") 0)
                      (parse-int-default (get attrs "x2") 0)
                      (parse-int-default (get attrs "y2") 0)])

      (= tag-name "rect")
      (record-create scene/rect-type
                     [node-id
                      nil
                      style
                      visible
                      (parse-int-default (get attrs "x") 0)
                      (parse-int-default (get attrs "y") 0)
                      (parse-int-default (get attrs "width") (parse-int-default (get attrs "w") 0))
                      (parse-int-default (get attrs "height") (parse-int-default (get attrs "h") 0))])

      (= tag-name "polyline")
      (record-create scene/polyline-type
                     [node-id
                      nil
                      style
                      visible
                      (parse-points (or (get attrs "points") ""))
                      false])

      (= tag-name "polygon")
      (record-create scene/polyline-type
                     [node-id
                      nil
                      style
                      visible
                      (parse-points (or (get attrs "points") ""))
                      true])

      :else nil)))

(defn- parse-tag-body
  [raw-tag node-id]
  (let [trimmed0 (str/trim raw-tag)
        trimmed (if (str/ends-with? trimmed0 "/")
                  (str/trim (subs trimmed0 0 (- (count trimmed0) 1)))
                  trimmed0)]
    (if (or (= trimmed "") (str/starts-with? trimmed "/"))
      [nil node-id]
      (let [split-pos (first-ws-index trimmed)
            tag-name (str/lower-case (if (nil? split-pos) trimmed (subs trimmed 0 split-pos)))
            attrs-str (if (nil? split-pos) "" (subs trimmed (+ split-pos 1)))
            attrs (parse-attrs attrs-str)
            style-map (parse-style-inline (get attrs "style"))
            node (node-from-tag tag-name attrs style-map node-id)]
        (if (nil? node)
          [nil node-id]
          [node (+ node-id 1)])))))

^#^{:doc "Parses an SVG string into a Group record for tiny-clj vector rendering.

MVP behavior:
- Supports line/rect/polyline/polygon tags.
- Produces Group/Line/Rect/Polyline/Style records with keyword fields used by C renderer.
- Coordinates are integer-based (decimal values are truncated).
- `fill` is parsed but currently only used as fallback stroke color until fill rasterization is available."}
(defn group-from-svg
  [svg-str]
  (scene/ensure-scene-records!)
  (if (or (nil? svg-str) (= (str/trim svg-str) ""))
    (record-create scene/group-type [1 nil nil true []])
    (loop [idx 0
           next-id 100
           nodes []]
      (let [lt (str/index-of svg-str "<" idx)]
        (if (nil? lt)
          (record-create scene/group-type [1 nil nil true nodes])
          (let [gt (str/index-of svg-str ">" (+ lt 1))]
            (if (nil? gt)
              (record-create scene/group-type [1 nil nil true nodes])
              (let [tag (subs svg-str (+ lt 1) gt)
                    parsed (parse-tag-body tag next-id)
                    node (first parsed)
                    id2 (nth parsed 1)]
                (if (nil? node)
                  (recur (+ gt 1) next-id nodes)
                  (recur (+ gt 1) id2 (conj nodes node)))))))))))
